package com.truemesh.squiggle;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * 
 * 
 *
 */
public class SqlConstants {
	
	public static final String CHILD_SEPARATOR = ".";
	public static final String LIST_SEPARATOR = ",";
	public static final String LIST_SEPARATOR_WITH_SPACE = LIST_SEPARATOR+" ";
	public static final String QUOTE = "\"";
	public static final String LITERAL = "'";
	public static final String SUB_CLAUSE_OPEN = "(";
	public static final String SUB_CLAUSE_CLOSE = ")";
	public static final String STATEMENT_TERMINATOR = ";";
	public static final String[] RESERVED_WORDS_ARRAY = new String[] {"ABSOLUTE","ADD","ALL","ALLOCATE","ALTER","AND","ANY","ARE","AS","ASC","ASSERTION","AT","AUTHORIZATION","AVG","BEGIN","BETWEEN","BIT","BIT_LENGTH","BOTH","BY","CASCADE","CASE","CAST |CHAR","CHARACTER","CHARACTER_LENGTH","CHAR_LENGTH","CHECK","CLOSE","COALESCE","COLLATE","COMMIT","CONNECT","CONNECTION","CONSTRAINT","CONSTRAINTS","CONTINUE","CONVERT","CORRESPONDING","COUNT","CREATE","CROSS","CURRENT","CURRENT_DATE","CURRENT_TIME","CURRENT_TIMESTAMP","CURRENT_USER","CURSOR","DATE","DEALLOCATE","DEC","DECIMAL","DECLARE","DEFAULT","DEFERRABLE","DEFERRED","DELETE","DESC","DESCRIBE","DESCRIPTOR","DIAGNOSTICS","DISCONNECT","DISTINCT","DOMAIN","DOUBLE","DROP","ELSE","END","ENDEXEC","ESCAPE","EXCEPT","EXCEPTION","EXEC","EXECUTE","EXISTS","EXTERNAL","EXTRACT","FALSE","FETCH","FIRST","FLOAT","FOR","FOREIGN","FOUND","FROM","FULL","GET","GLOBAL","GO","GOTO","GRANT","GROUP","HAVING","HOUR","IDENTITY","IMMEDIATE","IN","INDICATOR","INITIALLY","INNER","INPUT","INSENSITIVE","INSERT","INT","INTEGER","INTERSECT","INTERVAL","INTO","IS","ISOLATION","JOIN","LANGUAGE","LAST","LEADING","LEFT","LEVEL","LIKE","LOCAL","LOWER","MATCH","MAX","MIN","MINUTE","MODULE","NAMES","NATIONAL","NATURAL","NCHAR","NEXT","NO","NOT","NULL","NULLIF","NUMERIC","OCTET_LENGTH","OF","ON","ONLY","OPEN","OPTION","OR","OUTER","OUTPUT","OVERLAPS","PAD","PARTIAL","PREPARE","PRESERVE","PRIMARY","PRIOR","PRIVILEGES","PROCEDURE","PUBLIC","READ","REAL","REFERENCES","RELATIVE","RESTRICT","REVOKE","RIGHT","ROLE","ROLLBACK","ROWS","SCHEMA","SCROLL","SECOND","SECTION","SELECT","SESSION_USER","SET","SHARD","SMALLINT","SOME","SPACE","SQLERROR","SQLSTATE","STATISTICS","SUBSTRING","SUM","SYSDATE","SYSTEM_USER","TABLE","TEMPORARY","THEN","TIME","TIMEZONE_HOUR","TIMEZONE_MINUTE","TO","TOP","TRAILING","TRANSACTION","TRIM","TRUE","UNION","UNIQUE","UPDATE","UPPER","USER","USING","VALUES","VARCHAR","VARYING","WHEN","WHENEVER","WHERE","WITH","WORK","WRITE"};
	public static final Set<String> RESERVED_WORDS = new HashSet<String>(Arrays.asList(RESERVED_WORDS_ARRAY));

}
